apiVersion: apps/v1
kind: Deployment 
metadata:
  name: employee-app
  namespace: application
spec:
  replicas: 3
  selector:
   matchLabels:
    app: employee
  template:
    metadata:
      name: employee-app
      labels:
        app: employee
        env: Assignment2
        object: replicaset
    spec:
      containers:
        - name: app-rep
          image: 876560225863.dkr.ecr.us-east-1.amazonaws.com/ecr_assignment2:my_app_v0.1
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: DBHOST
            value: "10.244.0.30"
          - name: DBPORT
            value: "3306"
          - name: DBUSER
            value: "root"
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            value: "password"
          ports:
            - containerPort: 8080
              protocol: TCP

