apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: database
  labels:
    app: mysql
    env: Assignment2
    object: pod
spec:
  containers:
  - image: 876560225863.dkr.ecr.us-east-1.amazonaws.com/ecr_assignment2:my_db_v0.1
    name: mysql-pod
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 8080 
      protocol: TCP
    
